const List<Map<String, dynamic>> samplePlans = [
  {
    'title': 'MediCare LITE',
    'features': [
      'No Copay in Value network hospitals View List',
      'Yearly Free HealthCheckup',
    ],
    'amountYearly': '9428',
    'amountMonthly': '1569',
    'totalBenefits': '& 15 benefits in total',
    'whatIsNotIncluded': [
      'Domestic Emergency Assistance Services(including air ambulance) ',
      'Premium Waiver',
      'Vaccination Cover',
    ],
    'whatIsCovered': [
      'Compensative Travel',
      'Maternity Benefits',
      'Delivery Complications Cover',
      'First Year Vaccination Cover',
      '100% hospital bill paid* ',
      'Cumulative Bonus for Claim-free Years',
    ],
    'waitingPeriod': [
      '30 days waiting period for all illnesses',
      '24 months waiting period for specific illnesses',
      'Any pre-existing diseases will be covered after 48 months of continuous coverage',
      'Maternity benefits will be covered after 48 months of continuous coverage',
    ],
  },
  {
    'title': 'Medicare Premier',
    'features': [
      '100% hospital bill paid* ',
      'Cumulative Bonus for Claim-free Years',
    ],
    'amountYearly': '11909',
    'amountMonthly': '4524',
    'totalBenefits': '& 22 benefits in total',
    'whatIsNotIncluded': [
      'Domestic Emergency Assistance Services(including air ambulance) ',
      'International Emergency Assistance Services',
      'Premium Waiver',
      'Vaccination Cover',
      'OPD Cover',
    ],
    'whatIsCovered': [
      'High end Diagnostics',
      'OPD Treatment',
      'OPD Dental Treatment',
      'Global covered for planned Hospotalization',
      'Compensative Travel',
      'Maternity Benefits',
      'Delivery Complications Cover',
      'First Year Vaccination Cover',
      '100% hospital bill paid* ',
      'Cumulative Bonus for Claim-free Years',
    ],
    'waitingPeriod': [
      '30 days waiting period for all illnesses',
      '24 months waiting period for specific illnesses',
      'Any pre-existing diseases will be covered after 48 months of continuous coverage',
      'Maternity benefits will be covered after 48 months of continuous coverage',
    ],
  },
  {
    'title': 'Premier with Plus**',
    'features': [
      '100% hospital bill paid* ',
      '50% Increase in cumulative bonus ',
      'Health Checkup',
    ],
    'amountYearly': '9200',
    'amountMonthly': '3435',
    'totalBenefits': '& 28 benefits in total',
    'whatIsNotIncluded': [
      'Domestic Emergency Assistance Services(including air ambulance) ',
      'International Emergency Assistance Services',
      'Maternity Benefits',
      'Dental and Optical Benefits',
      'Premium Waiver',
      'Daily Allowance',
      'Vaccination Cover',
      'OPD Cover',
    ],
    'whatIsCovered': [
      'High end Diagnostics',
      'OPD Treatment',
      'OPD Dental Treatment',
      'Global covered for planned Hospotalization',
      'Compensative Travel',
      'Maternity Benefits',
      'Delivery Complications Cover',
      'First Year Vaccination Cover',
      '100% hospital bill paid* ',
      'Cumulative Bonus for Claim-free Years',
    ],
    'waitingPeriod': [
      '30 days waiting period for all illnesses',
      '24 months waiting period for specific illnesses',
      'Any pre-existing diseases will be covered after 48 months of continuous coverage',
      'Maternity benefits will be covered after 48 months of continuous coverage',
    ],
  },
];
